[package]
name = "snmp_rust_agent"
version = "0.1.0"
edition = "2021"

[dependencies]
rasn-snmp = "0.22.2"
rasn-smi = "0.22.2"
rasn = "0.22.2"
log = "0.4.22"
env_logger = "0.11.6"
sha1 = "0.10.6"
hex = "0.4.3"
regex = "1.11.1"
cfb-mode = "0.8.1"
aes = "0.8.4"