//! Stub loader generated by stub-gen.
//!
//! Do not edit - it will be over-written next time you run stub-gen
use crate::config::{ComplianceStatements, Config};
use crate::oidmap::OidMap;
use crate::snmp_agent::Agent;
use crate::usm::Users;
mod snmp_target_stub;
mod snmp_user_based_sm_stub;
mod snmpv2_stub;

///Generated function to load all stubs
pub fn load_stubs<'a>(
    oid_map: &'a mut OidMap,
    config: &Config,
    agent: &Agent,
    users: &'a Users,
    comp: &mut ComplianceStatements,
) {
    snmp_user_based_sm_stub::load_stub(oid_map, config, agent, users, comp);
    snmp_target_stub::load_stub(oid_map, agent, comp);
    // Do this one last, as it loads the gathered compliance statements
    snmpv2_stub::load_stub(oid_map, config, agent, comp);
}
