//! Stub loader generated by stub-gen.
//!
//! Do not edit - it will be over-written next time you run stub-gen
use crate::config::{ComplianceStatements, Config};
use crate::oidmap::OidMap;
use crate::snmp_agent::Agent;
use crate::usm::Users;
mod snmp_user_based_sm_stub;
mod snmpv2_stub;

///Generated function to load all stubs
pub fn load_stubs(
    oid_map: &mut OidMap,
    config: &Config,
    agent: &Agent,
    users: &Users,
    comp: &mut ComplianceStatements,
) {
    snmp_user_based_sm_stub::load_stub(oid_map, config, agent, users, comp);

    // Do this one last, as it loads the gtahered compliance statements
    snmpv2_stub::load_stub(oid_map, config, agent, comp);
}
