//! Stub loader generated by stub-gen.
//!
//! Do not edit - it will be over-written next time you run stub-gen
use crate::config::ComplianceStatements;
use crate::oidmap::OidMap;


///Generated function to load all stubs
pub fn load_stubs(oid_map: &mut OidMap, comp: &mut ComplianceStatements) {
    //  for example if_stub::load_stub(oid_map, comp);
}