//! Stub loader generated by stub-gen.
//!
//! Do not edit - it will be over-written next time you run stub-gen
use crate::oidmap::OidMap;
use crate::config::ComplianceStatements;



///Generated function to load all stubs
pub fn load_stubs(oid_map: &mut OidMap, comp: &mut ComplianceStatements) {
}
